### ISSUE TITLE
With a global them enabled, presenting a UIActivityViewController the "cancel" button is white on white

### ISSUE THREAD

**Issue by aventurella** [ViccAlexander/Chameleon#173] opened 2017-02-28 14:08 UTC
In my app delegate `didFinishLaunching` setting a global theme:

```
Chameleon.setGlobalThemeUsingPrimaryColor(UIColor.flatMagenta(), with: .light)
```
Then, in this case presenting a `UIActivityViewController` (aka Share sheet) *in this particular case the 1Password extension UIActivityViewController, but it's just this one line: https://github.com/AgileBits/onepassword-app-extension/blob/master/OnePasswordExtension.m#L66*

The `Cancel` button on the UIActivityViewController is not themed. It's just white on white.

**Comment by bre7** [comment] 2017-03-01 19:21
Dupe of #98 (check workaround)

Similar to #74 #102 #153

**Closed** 2017-03-01 19:22 UTC
Labels: Bug
