### ISSUE TITLE
Chameleon.setGlobalThemeUsingPrimaryColor adds background to UITableView accessory

### ISSUE THREAD

**Issue by AdrianBinDC** [ViccAlexander/Chameleon#153] opened 2016-10-18 18:38 UTC
This code is in my AppDelegate.swift file:
```swift
Chameleon.setGlobalThemeUsingPrimaryColor(FlatBlueDark(), withSecondaryColor: FlatPowderBlue(), andContentStyle: .light)
```

I also tried with this:
`Chameleon.setGlobalThemeUsingPrimaryColor(FlatBlueDark(), with: .light)`

It works beautifully until I get to my `UITableView`. On my `UITableView`, the color of my `checkmark` accessory is displayed as the theme color and the checkmark is inverted. **How do I get the checkmark to display just the theme color without a background behind it?**

![screen shot 2016-10-18 at 1 52 54 pm](https://cloud.githubusercontent.com/assets/10606010/19491306/824c22ce-9540-11e6-8328-de1c6438cb44.png)
 
![screen shot 2016-10-18 at 2 21 18 pm](https://cloud.githubusercontent.com/assets/10606010/19491316/878f6520-9540-11e6-9eef-e721138fb7d8.png)

**Comment by bre7** [comment] 2016-10-18 19:47
Dupe of #98 

Similar to #74 #102

**Closed by bre7** 2016-10-18 19:47 UTC
