### ISSUE TITLE
Gradient don't fit with my view

### ISSUE THREAD

**Issue by gabyalex** [ViccAlexander/Chameleon#65] opened 2015-10-07 12:06 UTC
Hi, i'm trying to add a gradient background for my UIView but, unfortunately, it don't fit with my desired width (screen width). The gradient contains black + transparent.

Code:
```swift
let colors:[UIColor] = [.blackColor(), .clearColor()]

fadeBackground.backgroundColor = GradientColor(.LeftToRight, fadeBackground.frame, colors)
```
*ps is my first project in iOS and i'm working with Swift

Portrait:

![screen shot 2015-10-07 at 14 51 53](https://cloud.githubusercontent.com/assets/5443491/10336919/ce9e9220-6d04-11e5-91bf-a0a1f5754d9a.png)

Landscape:

![screen shot 2015-10-07 at 14 49 56](https://cloud.githubusercontent.com/assets/5443491/10336927/e0bd8542-6d04-11e5-8109-528b06c1f376.png)

**Comment by bre7** [comment] 2015-10-07 12:41
(Cleaned your code a bit)

I've tried something similar with the demo project and it worked as intended. Maybe you forgot to set constraints for the fadeBackground UIView ?

**Comment by gabyalex** [comment] 2015-10-07 13:11
![screen shot 2015-10-07 at 16 10 23](https://cloud.githubusercontent.com/assets/5443491/10338310/120d2e32-6d0e-11e5-9496-3af1cebc96b6.png)

**Comment by bre7** [comment] 2015-10-07 13:15
Mmmh, I'm not sure then...I wasn't able to reproduce your issue.

Does that happen when orientation changes ? Or the moment the scene is shown ?

**Comment by gabyalex** [comment] 2015-10-07 14:17
It happen every time. Btw, i observed that a new gradient is created at the end of the main one. can i stop this? The only solution i found is to set the width of the frame = screen_width * 2.

**Comment by bre7** [comment] 2015-10-09 00:08
Are you able to share your code ? (If you don't want to or can't post it online, send me an email and I'll try to check if it's an issue related with Chameleon)

**Comment by ViccAlexander** [comment] 2015-10-09 01:29
Thanks @bre7 for helping out. @gabyalex How did you install Chameleon? Cocoapods or manually? Make sure you're using the latest release.

**Comment by weiFans** [comment] 2015-10-09 05:30
How not to receive mail message alerts？

**Comment by bre7** [comment] 2015-10-09 05:35
Stop watching the issue or disable email notifications.

**Comment by weiFans** [comment] 2015-10-09 05:57
@bre7 I closed the right side of the small speakers, but it will receive notification, trouble

**Comment by ViccAlexander** [comment] 2015-10-09 08:41
@weiFans At the top right corner of the page you'll see a few buttons, specifically one with an **eye**. Click on it and select `Ignoring`. This way you will no longer be notified about anything.

![ignoring](https://cloud.githubusercontent.com/assets/1724674/10389461/b12f28ee-6e26-11e5-9669-301c86695351.png)

**Comment by weiFans** [comment] 2015-10-09 09:21
@bre7 ths~

**Comment by ViccAlexander** [comment] 2015-10-16 21:46
I'm closing this issue for now seeing that I can't reproduce the bug either. If more information is provided we can reopen the issue.

**Closed** 2015-10-16 21:47 UTC
Labels: More Info Needed, No Issue
